spring:

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:6543/postgres
    username: postgres.logwpnwhrrdwbfylkvdu
    password: gisC!vL@tgXK4RE
  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true


jpa:
  properties:
    generate-ddl: true
    hibernate:
      format_sql: true
      highlight_sql: true
      use_sql_comments: true
      ddl-auto: create
      show-sql: true


logging:
  level:
    org.springframework.security: trace
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug

auth:
  jwt:
    issuer: com.sparta
    secret: sldjfnljsdhf109herhr810ntnekjf1jd
    accessTokenExpirationHour: 168